title: Bearing Man
description: Разборы, Эссе, Истории
lang: ru

# If publishing under a project site, set these:
# url: "https://<username>.github.io"
# baseurl: "/<repository>"

collections:
  essays:
    output: true
    permalink: /essays/:name/
  analyses:
    output: true
    permalink: /analyses/:name/
  stories:
    output: true
    permalink: /stories/:name/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: lsquo,rsquo,laquo,raquo

excerpt_separator: "<!--more-->"

# Defaults for the collections
defaults:
  - scope:
      path: ""
      type: essays
    values:
      layout: essay
      lang: ru
  - scope:
      path: ""
      type: analyses
    values:
      layout: essay
      lang: ru
  - scope:
      path: ""
      type: stories
    values:
      layout: essay
      lang: ru 